name: Pre-Commit

on:
  workflow_call:

env:
  PY_VERSION: "3.10"
  GO_VERSION: "^1.19.0"
  WORKFLOW_VERSION: "v0.1"

jobs:
  terraform_fmt:
    name: terraform_fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # tag=v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Checkout precommit config
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          repository: StratusGrid/workflow-config
          ref: ${{ env.WORKFLOW_VERSION }}
          path: workflow-config
      - name: Install Python ${{ env.PY_VERSION }}.X
        uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5 # tag=v4
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install TFenv
        run: |
          curl -fsSL -o install.sh https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
          brew install tfenv
          tfenv install
      - name: Install pre-commit dependencies
        run: |
          pip install pre-commit
      - name: Copy precommit config
        run: |
          cp -r workflow-config/precommit-config/. -t $GITHUB_WORKSPACE
      - name: Execute pre-commit
        run: |
          pre-commit run terraform_fmt --color=always --show-diff-on-failure --all-files
  

  terraform_tflint:
    name: terraform_tflint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # tag=v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Checkout precommit config
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          repository: StratusGrid/workflow-config
          ref: ${{ env.WORKFLOW_VERSION }}
          path: workflow-config
      - name: Install Python ${{ env.PY_VERSION }}.X
        uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5 # tag=v4
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install TFenv
        run: |
          curl -fsSL -o install.sh https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
          brew install tfenv
          tfenv install
      - name: Install pre-commit dependencies
        run: |
          pip install pre-commit
          brew install tflint
          tflint --init
      - name: Copy precommit config
        run: |
          cp -r workflow-config/precommit-config/. -t $GITHUB_WORKSPACE
      - name: Execute pre-commit
        run: pre-commit run terraform_tflint --color=always --show-diff-on-failure --all-files

  terraform_docs:
    name: terraform_docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # tag=v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Checkout precommit config
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          repository: StratusGrid/workflow-config
          ref: ${{ env.WORKFLOW_VERSION }}
          path: workflow-config
      - name: Install Python ${{ env.PY_VERSION }}.X
        uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5 # tag=v4
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install TFenv
        run: |
          curl -fsSL -o install.sh https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
          brew install tfenv
          tfenv install
      - name: Install pre-commit dependencies
        run: |
          pip install pre-commit
          brew install terraform-docs
      - name: Copy precommit config
        run: |
          cp -r workflow-config/precommit-config/. -t $GITHUB_WORKSPACE
      - name: Execute pre-commit
        run: pre-commit run terraform_docs --color=always --show-diff-on-failure --all-files

  check-yaml:
    name: check-yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # tag=v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Checkout precommit config
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          repository: StratusGrid/workflow-config
          ref: ${{ env.WORKFLOW_VERSION }}
          path: workflow-config
      - name: Install Python ${{ env.PY_VERSION }}.X
        uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5 # tag=v4
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install pre-commit dependencies
        run: |
          pip install pre-commit
      - name: Copy precommit config
        run: |
          cp -r workflow-config/precommit-config/. -t $GITHUB_WORKSPACE
      - name: Execute pre-commit
        run: pre-commit run check-yaml --color=always --show-diff-on-failure --all-files

  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # tag=v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Checkout precommit config
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          repository: StratusGrid/workflow-config
          ref: ${{ env.WORKFLOW_VERSION }}
          path: workflow-config
      - name: Install Python ${{ env.PY_VERSION }}.X
        uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5 # tag=v4
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install pre-commit dependencies
        run: |
          pip install pre-commit
      - name: Copy precommit config
        run: |
          cp -r workflow-config/precommit-config/. -t $GITHUB_WORKSPACE
      - name: Execute pre-commit
        run: pre-commit run prettier --color=always --show-diff-on-failure --all-files

  terraform_validate:
    name: terraform_validate
    runs-on: ubuntu-latest
    needs:
      [terraform_fmt, check-yaml, prettier, terraform_tflint, terraform_docs]
    steps:
      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # tag=v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Checkout precommit config
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          repository: StratusGrid/workflow-config
          ref: ${{ env.WORKFLOW_VERSION }}
          path: workflow-config
      - name: Check if GitHub App is provided
        id: check-github-app
        if: "${{ env.TF_AUTOMATION_APP_ID != '' }}"
        run: echo "::set-output name=defined::true"
        env:
            TF_AUTOMATION_APP_ID: ${{ secrets.TF_AUTOMATION_APP_ID }}
      - name: Terraform Automation get install token
        if: steps.check-github-app.outputs.defined == 'true'
        id: get-token
        # Action is pined to SHA to use thrid party action as recommended by GitHub:
        # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
        uses: getsentry/action-github-app-token@38a3ce582e170ddfe8789f509597c6944f2292a9 # v1.0.6
        with:
          app_id: ${{ secrets.TF_AUTOMATION_APP_ID }}
          private_key: ${{ secrets.TF_AUTOMATION_APP_PRIVATE_KEY }}
      - name: Config git
        if: steps.check-github-app.outputs.defined == 'true'
        run: |
          git config --global url."https://x-access-token:${{ steps.get-token.outputs.token }}@github.com".insteadOf "https://github.com"
      - name: Install Python ${{ env.PY_VERSION }}.X
        uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5 # tag=v4
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install TFenv
        run: |
          curl -fsSL -o install.sh https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
          brew install tfenv
          tfenv install
      - name: Install pre-commit dependencies
        run: |
          pip install pre-commit
      - name: Copy precommit config
        run: |
          cp -r workflow-config/precommit-config/. -t $GITHUB_WORKSPACE
      - name: Execute pre-commit
        run: pre-commit run terraform_validate --color=always --show-diff-on-failure --all-files

  terraform_tfsec:
    name: terraform_tfsec
    runs-on: ubuntu-latest
    needs: terraform_validate
    steps:
      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # tag=v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Checkout precommit config
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          repository: StratusGrid/workflow-config
          ref: ${{ env.WORKFLOW_VERSION }}
          path: workflow-config
      - name: Install Python ${{ env.PY_VERSION }}.X
        uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5 # tag=v4
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install TFenv
        run: |
          curl -fsSL -o install.sh https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
          brew install tfenv
          tfenv install
      - name: Install pre-commit dependencies
        run: |
          pip install pre-commit
          brew install tfsec
      - name: Copy precommit config
        run: |
          cp -r workflow-config/precommit-config/. -t $GITHUB_WORKSPACE
      - name: Execute pre-commit
        run: pre-commit run terraform_tfsec --color=always --show-diff-on-failure --all-files

  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    needs: terraform_validate
    steps:
      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # tag=v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Checkout precommit config
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          repository: StratusGrid/workflow-config
          ref: ${{ env.WORKFLOW_VERSION }}
          path: workflow-config
      - name: Install Python ${{ env.PY_VERSION }}.X
        uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5 # tag=v4
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install pre-commit dependencies
        run: |
          pip install pre-commit
      - name: Copy precommit config
        run: |
          cp -r workflow-config/precommit-config/. -t $GITHUB_WORKSPACE
      - name: Execute pre-commit
        run: pre-commit run gitleaks --color=always --show-diff-on-failure --all-files
