name: Pre-Commit

on:
  workflow_call:

env:
  ACTIONS_CHECKOUT_VERSION: "v3"
  ACTIONS_GITHUB_APP_TOKEN_VERSION: "38a3ce582e170ddfe8789f509597c6944f2292a9" # v1.0.6 - Action is pinned to SHA per GitHub Actions hardening guide: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
  ACTIONS_SETUP_GO_VERSION: "v3"
  ACTIONS_SETUP_PYTHON_VERSION: "v4"
  ACTIONS_TERRAFORM_DOCS_VERSION: "v1.0.0"
  GO_VERSION: "^1.19.0"
  PY_VERSION: "3.10"

jobs:
  terraform_fmt:
    name: terraform_fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@${{ env.ACTIONS_SETUP_GO_VERSION }}
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout
        uses: actions/checkout@${{ env.ACTIONS_CHECKOUT_VERSION }}
      - name: Checkout precommit config
        uses: actions/checkout@${{ env.ACTIONS_CHECKOUT_VERSION }}
        with:
          repository: StratusGrid/workflow-config
          path: workflow-config
      - name: Install Python ${{ env.PY_VERSION }}.X
        uses: actions/setup-python@${{ env.ACTIONS_SETUP_PYTHON_VERSION }}
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install TFenv
        run: |
          git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
          ln -sfn ~/.tfenv/bin/* /usr/local/bin
          tfenv install
          tfenv use
      - name: Install pre-commit dependencies
        run: |
          pip install pre-commit
      - name: Copy precommit config
        run: |
          cp -r -n workflow-config/precommit-config/. -t $GITHUB_WORKSPACE
      - name: Execute pre-commit
        run: |
          pre-commit run terraform_fmt --color=always --show-diff-on-failure --all-files

  terraform_tflint:
    name: terraform_tflint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@${{ env.ACTIONS_SETUP_GO_VERSION }}
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout
        uses: actions/checkout@${{ env.ACTIONS_CHECKOUT_VERSION }}
      - name: Checkout precommit config
        uses: actions/checkout@${{ env.ACTIONS_CHECKOUT_VERSION }}
        with:
          repository: StratusGrid/workflow-config
          path: workflow-config
      - name: Install Python ${{ env.PY_VERSION }}.X
        uses: actions/setup-python@${{ env.ACTIONS_SETUP_PYTHON_VERSION }}
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install pre-commit dependencies
        run: |
          pip install pre-commit
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      - name: Copy precommit config
        run: |
          cp -r -n workflow-config/precommit-config/. -t $GITHUB_WORKSPACE
      - name: Execute pre-commit
        run: pre-commit run terraform_tflint --color=always --show-diff-on-failure --all-files

  terraform_docs:
    name: terraform_docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@${{ env.ACTIONS_CHECKOUT_VERSION }}
      - name: Check terraform docs
        uses: terraform-docs/gh-actions@${{ env.ACTIONS_TERRAFORM_DOCS_VERSION }}
        with:
          working-dir: .
          config-file: .config/.terraform-docs.yml
          git-push: "false"
          fail-on-diff: "true"

  check-yaml:
    name: check-yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@${{ env.ACTIONS_SETUP_GO_VERSION }}
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout
        uses: actions/checkout@${{ env.ACTIONS_CHECKOUT_VERSION }}
      - name: Checkout precommit config
        uses: actions/checkout@${{ env.ACTIONS_CHECKOUT_VERSION }}
        with:
          repository: StratusGrid/workflow-config
          path: workflow-config
      - name: Install Python ${{ env.PY_VERSION }}.X
        uses: actions/setup-python@${{ env.ACTIONS_SETUP_PYTHON_VERSION }}
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install pre-commit dependencies
        run: |
          pip install pre-commit
      - name: Copy precommit config
        run: |
          cp -r -n workflow-config/precommit-config/. -t $GITHUB_WORKSPACE
      - name: Execute pre-commit
        run: pre-commit run check-yaml --color=always --show-diff-on-failure --all-files

  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@${{ env.ACTIONS_SETUP_GO_VERSION }}
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout
        uses: actions/checkout@${{ env.ACTIONS_CHECKOUT_VERSION }}
      - name: Checkout precommit config
        uses: actions/checkout@${{ env.ACTIONS_CHECKOUT_VERSION }}
        with:
          repository: StratusGrid/workflow-config
          path: workflow-config
      - name: Install Python ${{ env.PY_VERSION }}.X
        uses: actions/setup-python@${{ env.ACTIONS_SETUP_PYTHON_VERSION }}
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install pre-commit dependencies
        run: |
          pip install pre-commit
      - name: Copy precommit config
        run: |
          cp -r -n workflow-config/precommit-config/. -t $GITHUB_WORKSPACE
      - name: Execute pre-commit
        run: pre-commit run prettier --color=always --show-diff-on-failure --all-files

  terraform_validate:
    name: terraform_validate
    runs-on: ubuntu-latest
    needs:
      [terraform_fmt, check-yaml, prettier, terraform_tflint, terraform_docs]
    steps:
      - uses: actions/setup-go@${{ env.ACTIONS_SETUP_GO_VERSION }}
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout
        uses: actions/checkout@${{ env.ACTIONS_CHECKOUT_VERSION }}
      - name: Checkout precommit config
        uses: actions/checkout@${{ env.ACTIONS_CHECKOUT_VERSION }}
        with:
          repository: StratusGrid/workflow-config
          path: workflow-config
      - name: Check if GitHub App is provided
        id: check-github-app
        if: "${{ env.TF_AUTOMATION_APP_ID != '' }}"
        run: echo "::set-output name=defined::true"
        env:
          TF_AUTOMATION_APP_ID: ${{ secrets.TF_AUTOMATION_APP_ID }}
      - name: Terraform Automation get install token
        if: steps.check-github-app.outputs.defined == 'true'
        id: get-token
        uses: getsentry/action-github-app-token@${{ ACTIONS_GITHUB_APP_TOKEN_VERSION }}
        with:
          app_id: ${{ secrets.TF_AUTOMATION_APP_ID }}
          private_key: ${{ secrets.TF_AUTOMATION_APP_PRIVATE_KEY }}
      - name: Config git
        if: steps.check-github-app.outputs.defined == 'true'
        run: |
          git config --global url."https://x-access-token:${{ steps.get-token.outputs.token }}@github.com".insteadOf "https://github.com"
      - name: Install Python ${{ env.PY_VERSION }}.X
        uses: actions/setup-python@${{ env.ACTIONS_SETUP_PYTHON_VERSION }}
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install TFenv
        run: |
          git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
          ln -sfn ~/.tfenv/bin/* /usr/local/bin
          tfenv install
          tfenv use
      - name: Install pre-commit dependencies
        run: |
          pip install pre-commit
      - name: Copy precommit config
        run: |
          cp -r -n workflow-config/precommit-config/. -t $GITHUB_WORKSPACE
      - name: Execute pre-commit
        run: pre-commit run terraform_validate --color=always --show-diff-on-failure --all-files

  terraform_tfsec:
    name: terraform_tfsec
    runs-on: ubuntu-latest
    needs: terraform_validate
    steps:
      - uses: actions/setup-go@${{ env.ACTIONS_SETUP_GO_VERSION }}
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout
        uses: actions/checkout@${{ env.ACTIONS_CHECKOUT_VERSION }}
      - name: Checkout precommit config
        uses: actions/checkout@${{ env.ACTIONS_CHECKOUT_VERSION }}
        with:
          repository: StratusGrid/workflow-config
          path: workflow-config
      - name: Install Python ${{ env.PY_VERSION }}.X
        uses: actions/setup-python@${{ env.ACTIONS_SETUP_PYTHON_VERSION }}
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install pre-commit dependencies
        run: |
          pip install pre-commit
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      - name: Copy precommit config
        run: |
          cp -r -n workflow-config/precommit-config/. -t $GITHUB_WORKSPACE
      - name: Execute pre-commit
        run: pre-commit run terraform_tfsec --color=always --show-diff-on-failure --all-files

  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    needs: terraform_validate
    steps:
      - uses: actions/setup-go@${{ env.ACTIONS_SETUP_GO_VERSION }}
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout
        uses: actions/checkout@${{ env.ACTIONS_CHECKOUT_VERSION }}
      - name: Checkout precommit config
        uses: actions/checkout@${{ env.ACTIONS_CHECKOUT_VERSION }}
        with:
          repository: StratusGrid/workflow-config
          path: workflow-config
      - name: Install Python ${{ env.PY_VERSION }}.X
        uses: actions/setup-python@${{ env.ACTIONS_SETUP_PYTHON_VERSION }}
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install pre-commit dependencies
        run: |
          pip install pre-commit
      - name: Copy precommit config
        run: |
          cp -r -n workflow-config/precommit-config/. -t $GITHUB_WORKSPACE
      - name: Execute pre-commit
        run: pre-commit run gitleaks --color=always --show-diff-on-failure --all-files
