name: Pre-Commit

on:
  workflow_call:

env:
  PY_VERSION: "3.x"
  GO_VERSION: "^1.22.0"
  OS_RUNNER_VERSION: "24.04"

jobs:
  terraform_fmt:
    name: terraform_fmt
    runs-on: ubuntu-${{ env.OS_RUNNER_VERSION }}
    steps:
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Checkout precommit config
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          repository: StratusGrid/workflow-config
          path: workflow-config
      - name: Install Python ${{ env.PY_VERSION }}.X
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install TFenv
        run: |
          git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
          ln -sfn ~/.tfenv/bin/* /usr/local/bin
          tfenv install
          tfenv use
      - name: Install pre-commit dependencies
        run: |
          pip install pre-commit
      - name: Copy precommit config
        run: |
          cp -r -n workflow-config/precommit-config/. -t $GITHUB_WORKSPACE
      - name: Execute pre-commit
        run: |
          pre-commit run terraform_fmt --color=always --show-diff-on-failure --all-files

  terraform_tflint:
    name: terraform_tflint
    runs-on: ubuntu-${{ env.OS_RUNNER_VERSION }}
    steps:
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Checkout precommit config
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          repository: StratusGrid/workflow-config
          path: workflow-config
      - name: Install Python ${{ env.PY_VERSION }}.X
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install pre-commit dependencies
        run: |
          pip install pre-commit
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      - name: Copy precommit config
        run: |
          cp -r -n workflow-config/precommit-config/. -t $GITHUB_WORKSPACE
      - name: Execute pre-commit
        run: pre-commit run terraform_tflint --color=always --show-diff-on-failure --all-files

  terraform_docs:
    name: terraform_docs
    runs-on: ubuntu-${{ env.OS_RUNNER_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Check terraform docs
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: .
          config-file: .config/.terraform-docs.yml
          git-push: "false"
          fail-on-diff: "true"

  check-yaml:
    name: check-yaml
    runs-on: ubuntu-${{ env.OS_RUNNER_VERSION }}
    steps:
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Checkout precommit config
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          repository: StratusGrid/workflow-config
          path: workflow-config
      - name: Install Python ${{ env.PY_VERSION }}.X
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install pre-commit dependencies
        run: |
          pip install pre-commit
      - name: Copy precommit config
        run: |
          cp -r -n workflow-config/precommit-config/. -t $GITHUB_WORKSPACE
      - name: Execute pre-commit
        run: pre-commit run check-yaml --color=always --show-diff-on-failure --all-files

  prettier:
    name: prettier
    runs-on: ubuntu-${{ env.OS_RUNNER_VERSION }}
    steps:
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Checkout precommit config
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          repository: StratusGrid/workflow-config
          path: workflow-config
      - name: Install Python ${{ env.PY_VERSION }}.X
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install pre-commit dependencies
        run: |
          pip install pre-commit
      - name: Copy precommit config
        run: |
          cp -r -n workflow-config/precommit-config/. -t $GITHUB_WORKSPACE
      - name: Execute pre-commit
        run: pre-commit run prettier --color=always --show-diff-on-failure --all-files

  terraform_validate:
    name: terraform_validate
    runs-on: ubuntu-${{ env.OS_RUNNER_VERSION }}
    needs:
      [terraform_fmt, check-yaml, prettier, terraform_tflint, terraform_docs]
    steps:
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Checkout precommit config
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          repository: StratusGrid/workflow-config
          path: workflow-config
      - name: Check if GitHub App is provided
        id: check-github-app
        if: "${{ env.TF_AUTOMATION_APP_ID != '' }}"
        run: echo "{name}={value}" >> $GITHUB_OUTPUT
        env:
          TF_AUTOMATION_APP_ID: ${{ secrets.TF_AUTOMATION_APP_ID }}
      - name: Terraform Automation get install token
        if: steps.check-github-app.outputs.defined == 'true'
        id: get-token
        # Action is pined to SHA to use thrid party action as recommended by GitHub:
        # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
        uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc # v3.0.0
        with:
          app_id: ${{ secrets.TF_AUTOMATION_APP_ID }}
          private_key: ${{ secrets.TF_AUTOMATION_APP_PRIVATE_KEY }}
      - name: Config git
        if: steps.check-github-app.outputs.defined == 'true'
        run: |
          git config --global url."https://x-access-token:${{ steps.get-token.outputs.token }}@github.com".insteadOf "https://github.com"
      - name: Install Python ${{ env.PY_VERSION }}.X
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install TFenv
        run: |
          git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
          ln -sfn ~/.tfenv/bin/* /usr/local/bin
          tfenv install
          tfenv use
      - name: Install pre-commit dependencies
        run: |
          pip install pre-commit
      - name: Copy precommit config
        run: |
          cp -r -n workflow-config/precommit-config/. -t $GITHUB_WORKSPACE
      - name: Execute pre-commit
        run: pre-commit run terraform_validate --color=always --show-diff-on-failure --all-files

  terraform_trivy:
    name: terraform_trivy
    runs-on: ubuntu-${{ env.OS_RUNNER_VERSION }}
    needs: terraform_validate
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          hide-progress: false
          exit-code: "1"
          scanners: "vuln,secret,misconfig"
          severity: "CRITICAL,HIGH"
          skip-dirs: ".terraform/*"

  gitleaks:
    name: gitleaks
    runs-on: ubuntu-${{ env.OS_RUNNER_VERSION }}
    needs: terraform_validate
    steps:
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Checkout precommit config
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          repository: StratusGrid/workflow-config
          path: workflow-config
      - name: Install Python ${{ env.PY_VERSION }}.X
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install pre-commit dependencies
        run: |
          pip install pre-commit
      - name: Copy precommit config
        run: |
          cp -r -n workflow-config/precommit-config/. -t $GITHUB_WORKSPACE
      - name: Execute pre-commit
        run: pre-commit run gitleaks --color=always --show-diff-on-failure --all-files
